sudo: required
services:
  - docker

before_install:
  - docker build -t msiddiq17328/docker_web_app -f Dockerfile.dev .

script:
  - docker run -e CI=true msiddiq17328/docker_web_app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker_react_travis_ci"
  env: "Dockerreacttravisci-env"
  bucket: "arn:aws:s3:::elasticbeanstalk-eu-north-1-789923323709"
  on:
    branch: master
  access_key_id: "AKIA3P2YZL46QOTQPP35"
  secret_access_key: "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"