sudo: required
services:
  - docker

before_install:
  - docker build -t msiddiq17328/docker_web_app -f Dockerfile.dev .

script:
  - docker run -e CI=true msiddiq17328/docker_web_app npm run test -- --coverage