sudo: required
services:
  - docker

before_install:
  - docker build -t msiddiq17328/docker_web_app -f Dockerfile.dev .

script:
  - docker run -e CI=true msiddiq17328/docker_web_app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-tra"
  env: "Docker-tra-env"
  bucket_name: "elasticbeanstalk-us-east-1-789923323709"
  bucket_path: "docker-tra"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY